defaults:
  - _self_
  - dataset: CRC
  - ctt: CRC
  - cls: CRC
  - augment: CRC

dataset_name: "CRC"
seeds: [3407, 2026, 0, 4, 23]

hydra:
  run:
    dir: outputs/${dataset_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}